### ISSUE TITLE
Image Support

### ISSUE THREAD

**Issue by Warnthebase** [v411e/hasswebhookbot#13]
Can an example YAML be provided for image support (#11)?
@v411e @AlexanderBabel 

This **does not** work:

```
service: notify.hass_maubot
data:
  message: None
  data:
    type: image
    image: <url>
```

**Comment by AlexanderBabel** [comment]
Yes sure. I used base64 encoding to pass the picture towards the bot. Here is a code example where I use the bot endpoint:
https://github.com/AlexanderBabel/mail-parser/blob/main/src/mail/services/parsers/mail.announcement.parser.service.ts#L33C1-L36C26
https://github.com/AlexanderBabel/mail-parser/blob/main/src/mail/services/push.service.ts#L65

```
data:
      contentType: "image/jpeg",
      content: "BASE64 String",
      name: "image-name.jpg",
      thumbnailSize: 512,
```

**Comment by Warnthebase** [comment]
Thanks for the quick response. Unfortunately, I still cannot get it to work:

I tried a few variations of this:

```
service: notify.hass_maubot
data:
  message: None
  data:
    contentType: "image/jpeg",
    content: "BASE64-String",
    name: "https://<public HA address>/local/image.jpg",
    thumbnailSize: "512",

```

Local image name did not work as well:

`name: "/local/image.jpg"`

Maubot log:

```
[INFO@maubot.instance.ha-maubot] Request for room !<room ID> data: {"message": "None", "type": "", "identifier": "", "callback_url": "", "lifetime": ""}
[DEBUG@maubot.instance.ha-maubot] {'message': 'None', 'type': '', 'identifier': '', 'callback_url': '', 'lifetime': ''}
[DEBUG@maubot.instance.ha-maubot] Lifetime: -1
[INFO@maubot.instance.ha-maubot] None
[DEBUG@maubot.instance.ha-maubot] Received data with ID !<room ID>: {'message': 'None', 'type': '', 'identifier': '', 'callback_url': '', 'lifetime': ''}
```

HA reformatted to:

```
service: notify.hass_maubot
data:
  message: None
  data:
    contentType: image/jpeg
    content: BASE64-String
    name: https://<public HA address>/local/image.jpg
    thumbnailSize: "512"
```

HA log showing nothing out of the ordinary

```
WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'identifier' when rendering '{{data.identifier}}'
WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'callback_url' when rendering '{{data.callback_url}}'
WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'lifetime' when rendering '{{data.lifetime}}'
```

As expected, I get a 404 with an n invalid `type`,

```
service: notify.hass_maubot
data:
  message: The quick brown fox jumps over the lazy dog
  data:
    type: Computer
```

`ERROR (MainThread) [homeassistant.components.rest.notify] Client error. Response 404: Not Found: NoneType: None`

I also edited my first post https://github.com/v411e/hasswebhookbot/issues/13#issue-1842193625 to show the Home Assistant log on that particular service call.

**Comment by v411e** [comment]
Oh, sorry for the late reply. I think there is a misunderstanding happening here :)
The image can not be referenced as a file, but instead has to be translated to BASE64 first. The `BASE64-String` part should be replaced by the actual content and does not define a type or something like that.

I will document this properly and then close this issue :)

**Comment by Warnthebase** [comment]
Thanks for all of your help @v411e , it is appreciated!

I was completely unaware that the `BASE64-String` had to be an actual string (silly me)! However, I am still unable to get this to work. 

Home Assistant rejects this:

```
service: notify.hass_maubot
data:
  data:
    contentType: image/jpeg
    content: <a very long BASE64-string>
    name: pizza.jpg
    thumbnailSize: 512
  message: None

```
`Failed to call service notify.hass_maubot. required key not provided @ data['message']. Got None`

Makes a bit of sense, it is looking for `message`, so we add it in:

```
service: notify.hass_maubot
data:
  message: None
  data:
    contentType: image/jpeg
    content: <a very long BASE64-string>
    name: pizza.jpg
    thumbnailSize: 512
```

Which simply outputs the message "none" into the matrix room. It does not display an image.

I also tried different variations of `type `and `contentType`. I do not get an error in Home Assistant, but no message (or image) is displayed.

For a long shot, I also tried adding `image: "{{data.image}}"` to the notify yaml in Home Assistant, but that did not have any effect.

Would you be able to provide a direct example that can be used in Home Assistant?
