### ISSUE TITLE
[Feature] Message lifetime

### ISSUE THREAD

**Issue by v411e** [v411e/hasswebhookbot#4]
It would be great if messages could be deleted by the bot after a given time. This would lead to cleaner rooms.

A `lifetime`attribute could be added (time in minutes)

A message then could look like this:
```yaml
service: notify.hass_maubot
data:
  message: Die Post ist da! 📬
  data:
    type: message
    identifier: letterbox.status
    lifetime: 1440
```
